# Aprendendo Numpys - Parte 2

Paulo Cysne Rios Jr., Oct 18, 2017

In [1]:
import numpy as np

## 1. Comparação, Mascas, Lógica Boolena

In [2]:
x = np.array([1, 2, 3, 4, 5])

In [3]:
x < 3

array([ True,  True, False, False, False], dtype=bool)

In [4]:
x >= 3

array([False, False,  True,  True,  True], dtype=bool)

In [5]:
x != 3

array([ True,  True, False,  True,  True], dtype=bool)

In [6]:
x == 3

array([False, False,  True, False, False], dtype=bool)

In [7]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False], dtype=bool)

## 2. Operações booleanas

In [8]:
bool(42), bool(0)

(True, False)

In [9]:
bool(42 and 0)

False

In [10]:
 bool(42 or 0)

True

In [11]:
A = np.array([1, 0, 1, 0, 1, 0], dtype=bool) 
B = np.array([1, 1, 1, 0, 1, 1], dtype=bool) 
A|B

array([ True,  True,  True, False,  True,  True], dtype=bool)

## 3. Arrays com booleans

In [12]:
rng = np.random.RandomState(0)
x = rng.randint(10, size=(3, 4))
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [13]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]], dtype=bool)

In [14]:
print(x)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


In [15]:
# how many values less than 6?
np.count_nonzero(x < 6)

8

In [16]:
np.sum(x < 6)

8

In [17]:
# how many values less than 6 in each row? 
np.sum(x < 6, axis=1)

array([4, 2, 2])

In [18]:
# are there any values greater than 8? 
np.any(x > 8)

True

In [19]:
# are there any values less than zero? 
np.any(x < 0)

False

In [20]:
# are all values less than 10? 
np.all(x < 10)

True

In [21]:
# are all values equal to 6? 
np.all(x == 6)

False

In [22]:
# are all values in each row less than 8? 
np.all(x < 8, axis=1)

array([ True, False,  True], dtype=bool)

## 4. Máscaras

In [23]:
x

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

In [24]:
x < 5

array([[False,  True,  True,  True],
       [False, False,  True, False],
       [ True,  True, False, False]], dtype=bool)

In [25]:
x[x < 5]

array([0, 3, 3, 3, 2, 4])

## 5. Classificando (sorting) arrays

### 5.1 Classificando vetores

In [26]:
x = np.array([2, 1, 4, 3, 5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [27]:
x.sort() 
print(x)

[1 2 3 4 5]


In [28]:
np.max(x)

5

In [29]:
np.argmax(x) # posição

4

In [30]:
x = np.array([2, 1, 4, 3, 5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [31]:
x[i]

array([1, 2, 3, 4, 5])

### 5.2 Classificando matrizes

In [32]:
rand = np.random.RandomState(42) 
X = rand.randint(0, 10, (4, 6)) 
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [33]:
# sort each column of X 
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [34]:
# sort each row of X 
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## 6. Centrando um array

In [35]:
X = np.random.random((10, 3))

In [36]:
X

array([[ 0.14346076,  0.24619011,  0.23077268],
       [ 0.05614917,  0.58246344,  0.94026678],
       [ 0.2431589 ,  0.35582313,  0.98394595],
       [ 0.36810125,  0.82358311,  0.8384655 ],
       [ 0.13311198,  0.32573958,  0.53892207],
       [ 0.94978186,  0.81303681,  0.14412517],
       [ 0.73211837,  0.60537157,  0.21557817],
       [ 0.55596214,  0.63939372,  0.793622  ],
       [ 0.17866272,  0.44601945,  0.40438487],
       [ 0.33807542,  0.46036474,  0.52266867]])

In [37]:
Xmean = X.mean(axis = 0)
Xmean

array([ 0.36985826,  0.52979857,  0.56127519])

In [38]:
X_centered = X - Xmean

In [39]:
X_centered

array([[-0.2263975 , -0.28360846, -0.3305025 ],
       [-0.31370909,  0.05266488,  0.3789916 ],
       [-0.12669936, -0.17397544,  0.42267076],
       [-0.00175701,  0.29378455,  0.27719031],
       [-0.23674628, -0.20405898, -0.02235312],
       [ 0.57992361,  0.28323824, -0.41715002],
       [ 0.36226011,  0.07557301, -0.34569702],
       [ 0.18610388,  0.10959515,  0.23234681],
       [-0.19119554, -0.08377911, -0.15689031],
       [-0.03178284, -0.06943383, -0.03860652]])

In [40]:
X_centered.mean(axis = 0)

array([  4.44089210e-17,   2.22044605e-17,  -1.11022302e-17])