# Aprendendo Numpys

Paulo Cysne Rios Jr., Oct 17, 2017

In [1]:
import numpy as np

In [2]:
np.__version__

'1.12.1'

## 1. Arrays

Arrays são estruturas da package Numpy
que podem ter qualquer números de dimensões
de 1 a N dimensões.
Os elementos de um array são todos numéricos e do mesmo tipo, podendo ser 
do tipo inteiro ou decimal.

Um array tem um forma (shape) que é dado 
- por um número quando se tem somente uma dimensão ou
- por uma tupla quando se tem mais do que uma dimensão.

Por exemplo,
- Um array com formato 5 seria um array de uma dimensão, chamado de vetor, com 5 elementos.
- Um array com formato (3, 2) é um array de 2 dimensões, com 3 linhas e 2 colunas, tendo 3x2 = 6 elementos.
- Um array com formato (3, 1, 4) é um array de 3 dimensões, com 3x1x4 = 12 elementos.

## 2. Criando arrays

### 2.1 Usando listas

Se pode criar arrays a partir de listas

In [3]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Quando há elementos de diferentes tipos,
o tipo mais geral deles é usado para todos.

In [4]:
# Todos são tranformados para o tipo decimal
np.array([3.14, 4, 2, 3])

array([ 3.14,  4.  ,  2.  ,  3.  ])

É também possível criar um array e especificar o tipo
de seus elementos.

In [5]:
np.array([1, 2, 3, 4], dtype='float32')

array([ 1.,  2.,  3.,  4.], dtype=float32)

Se pode criar arrays a partir de geradores do Python

In [6]:
# arrays multidimensionais
np.array([range(i, i + 3) for i in [2, 4]])

array([[2, 3, 4],
       [4, 5, 6]])

### 2.2 Usando np.zeros

np.zeros cria arrays onde todos os elementos são zeros.
Primeiro se diz o formato do array e com dtype se pode
dar o tipo (inteiro, decimal de 32 bits, decimal de 64 bits).

In [7]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

O padrão (default) são números reais caso não se der o tipo com *dtype*

In [8]:
np.zeros( (2, 3))  

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

### 2.3 Usando np.ones

Com np.ones, se pode criar arrays onde todos elementos tem valor 1.
Se passa primeiro a forma do array e depois, opcionalmente, o tipo desejado dos elementos do array.

In [9]:
np.ones((3, 4), dtype=float)

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

### 2.4 Usando np.full

Com np.full, se pode criar um array de formato (3, 4), quer dizer,
de 3 linhas e 4 colunas, com todos
elementos do array tendo valor 17.20

In [10]:
np.full((3, 4), 17.20)

array([[ 17.2,  17.2,  17.2,  17.2],
       [ 17.2,  17.2,  17.2,  17.2],
       [ 17.2,  17.2,  17.2,  17.2]])

### 2.5 Usando np.arange

Com np.arange, se pode criar um array a partir de um intervalo, começando no primeiro valor dado até o último, saltando de 1 em 1 ou saltando de acordo com o número dado.
Por exemplo, crie um array começando em 5, terminando no 15, 
indo de 3 em 3. Isto é similar a função do Python *range()*.

In [11]:
np.arange(5, 15, 3)

array([ 5,  8, 11, 14])

A função range() do Python se comporta de maneira
semelhante, mas ela não cria um array

In [12]:
for i in range(5, 15, 2):
    print(i)

5
7
9
11
13


### 2.6 Usando np.linspace

Com np.linspace se pode criar um array com um certo nr_de_elementos
igualmente espaçados entre os números nr1 e nr2, da seguinte maneira:
- np.linspace(nr1, nr2, nr_de_elementos)

Por exemplo, crie um array de 5 elementos
igualmente espaçados entre 1 e 23:

In [13]:
np.linspace(1, 23, 5)

array([  1. ,   6.5,  12. ,  17.5,  23. ])

### 2.7 Usando np.eye

Se pode criar uma matriz identidade usando np.eye. Desta forma basta passar um número inteiro para definir o formato da matriz já que ela terá o mesmo número de linhas e colunas, definidos pelo número passado, com todos os elementos iguais a zero, com exceção da sua diagonal que tem todos elementos igual a 1.

Por exemplo, crie uma matrix identidade 5x5:

In [14]:
 np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])

### 2.8 Usando números aleatórios

As funções que estão no modulo np.random criam arrays com números aleatórios. 

### 2.8.1 Reprodutibilidade com np.random.seed()

A função **np.random.seed()** define um valor semente para geração de valores aleatórios. 
Uma vez que se use o mesmo valor semente, os números aleatórios serão os mesmos. Esta é uma maneira de se conseguir *reprodutibilidade*, ou seja, que seja possível reproduzir um estudo feito com números aleatórios.

Exemplo: np.random.seed(5)

Se usarmos 5 como semente geradora, os números aleatórios criados pelas diferentes funções de np.random serão sempre os mesmos. Um outra pessoa usando a função np.random.seed() com semente = 5 como acima terá os mesmos números aleatórios que obtivemos.

### 2.8.2 Uniformemente distribuídos

Com np.random.random se pode criar arrays do formato dado, com elementos que são aleatórios e uniformemente distribuidos entre 0 e 1.

Por exemplo, crie um array for formato 3x2 com números aleatórios uniformemente distribuídos entre 0 e 1: 

In [15]:
np.random.random((3, 2))

array([[ 0.6081733 ,  0.12567923],
       [ 0.44210391,  0.19036424],
       [ 0.71015024,  0.92605126]])

### 2.8.3 Com distribuição normal

Se pode criar arrays com elementos que seguem a distribuição normal (com formato de um sino), passando a média e o desvio padrão da distribuição normal a ser criada.

Por exemplo, para simular alturas de pessoas, crie um array 3x2, com média 176 (para representar 176 cm = 1.76 m), e desvio padrão 10:

In [16]:
np.random.normal(176, 10, (3, 2))

array([[ 162.52413991,  174.10329192],
       [ 177.67706453,  176.34621565],
       [ 179.91596028,  183.32656714]])

### 2.8.4 Somente com números inteiros

Se pode criar um array cujos elementos são todos inteiros, do formato dado, dentro do intervalo dado entre o primeiro e segundo número passado.

Por exemplo, crie um array de inteiros do formato 4x2 no intervalo de 1 a 60: 

In [17]:
np.random.randint(1, 60, (4, 2))

array([[53,  6],
       [32, 35],
       [49, 39],
       [ 8,  1]])


## 3. Atributos

Todo array possue vários atributos que o definem. Eles são:
- Seu número de dimensões (ndim)
- Seu formato (shape)
- Seu número de elementos (size)
- O tipo dos seus elementos (dtype)
- Quantos bytes cada um de seus elementos ocupa na memória do computador (itemsize)
- Quantos bytes seus elementos como um todo ocupa na memória do computador (nbytes)


Definiremos 3 variáveis com arrays de diferentes formatos para checarmos seus atributos posteriormente.

Semente para reprodutibilidade:

In [18]:
np.random.seed(0) 

Array com numeros inteiros aleatórios de 0 a 10
postos num formato de 1 dimensão com 6 elementos:

In [19]:
x1 = np.random.randint(10, size=6)

Array com numeros inteiros aleatórios de 0 a 10
postos num formato de 2 dimensões com 3x4 = 12 elementos:

In [20]:
x2 = np.random.randint(10, size=(3, 4))

Array com numeros inteiros aleatórios de 0 a 10
postos num formato de 3 dimensões com 3x4x5 = 12 elementos:

In [21]:
x3 = np.random.randint(10, size=(3, 4, 5))

In [22]:
x1

array([5, 0, 3, 3, 7, 9])

In [23]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [24]:
x2.ndim

2

In [25]:
x2.shape

(3, 4)

In [26]:
x2.size

12

In [27]:
print("x3 ndim: ", x3.ndim) 
print("x3 shape:", x3.shape) 
print("x3 size: ", x3.size) 

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [28]:
print("dtype:", x3.dtype)

dtype: int64


In [29]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


## 4. Indexação

Se pode obter um elemento de um array facilmente, bastando passar como argumento dentro de  [] a posição do elemento. 

É bom lembrar que as posições começam com 0 no sentido da esquerda para a direita e com -1 no sentido da direita para a esquerda. Assim, 
- com 0 temos o elemento na primeira posição  
- com -1 o elemento na última posição
- com 1 o elemento na segunda posição
- com -2 o elemento na penúltima posição

###  4.1 Indexação de vetores

In [30]:
x1

array([5, 0, 3, 3, 7, 9])

In [31]:
x1[0]

5

In [32]:
x1[-1]

9

In [33]:
x1[5]

9

In [34]:
# Posição 5 é a última em x1
x1[-1] == x1[5]

True

### 4.2 Indexação de matrizes

Para se obter um elemento que está em uma certa linha e uma certa coluna, basta passar no formato [linha, coluna], lembrando que as posições começam de 0 e no sentido contrário começam de -1.

In [35]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [36]:
x2[0,0]

3

In [37]:
x2[0, 3]

4

In [38]:
x2[0, -1]

4

In [39]:
x2[2, 0]

1

In [40]:
x2[2, -1]

7

## 4.3 Fatiamento (Slicing)

Usando o símbolo *:* se pode obter fatias de arrays. O formato é *de:para*. Quando o "de" for omitido, significa a partir do ínicio. Quando o "para" for omitido, significa até o final.

O formato *de:para:passo* significa a partir da posição "de" até a posição "para" saltando de "passo" em "passo".  Quando passo for omitido, ficando da forma mais simples de:para, isto significa que passo é igual a 1.

### 4.3.1 Fatiamento em uma dimensão

In [41]:
x = np.arange(10)

In [42]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Os primeiros cinco elementos:

In [43]:
x[:5] 

array([0, 1, 2, 3, 4])

Elementos depois da posição/índice 5:

In [44]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
x[5:] 

array([5, 6, 7, 8, 9])

Fatia no meio da posição 4 até a posição 7 (esta não inclusive):

In [46]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
x[4:7] 

array([4, 5, 6])

Um elemento sim outro não (de 2 em 2):

In [48]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x[::2] 

array([0, 2, 4, 6, 8])

Da posição 3 até a posição 8 (não inclusive) indo de 2 em 2:

In [50]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
x[3:8:2]

array([3, 5, 7])

Começando na posição/índice 1, de 2 em 2, até o final:

In [52]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
x[1::2] 

array([1, 3, 5, 7, 9])

Ordem reversa, do fim para o ínicio, todos os elementos:

In [54]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

Da posição/índice 4 até o final, mas em ordem reversa (veja o -1):

In [56]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
x[4::-1]

array([4, 3, 2, 1, 0])

Da posição 5 em order reversa de 2 em 2 (veja o -2):

In [58]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
x[5::-2] 

array([5, 3, 1])

### 4.3.2 Fatiamento em mais de 1 dimensão, multidimensional

In [60]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

Até a linha de posição/índice 2 (esta não inclusive), até coluna de posição/índice 3 (esta não inclusive):

In [61]:
x2[:2, :3] 

array([[3, 5, 2],
       [7, 6, 8]])

Até a linha com índice 2 (não inclusive), da coluna de índice 1 até a coluna de índice 4 (não inclusive)

In [62]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [63]:
x2[ :2, 1:4 ]

array([[5, 2, 4],
       [6, 8, 8]])

Até a linha de índice 3 (não inclusive), todas as colunas de 2 em 2

In [64]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [65]:
x2[:3, ::2] 

array([[3, 2],
       [7, 8],
       [1, 7]])

Todas as linhas de forma reversa (-1), todas as colunas de forma reversa (-1)

In [66]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [67]:
x2[::-1, ::-1]

array([[7, 7, 6, 1],
       [8, 8, 6, 7],
       [4, 2, 5, 3]])

Imprimindo todas as linhas de x2 e a sua coluna de índice 0:

In [68]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [69]:
print(x2[:, 0]) # first column of x2

[3 7 1]


Imprimindo a primeira linha de x2 e todas as suas colunas:

In [70]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [71]:
 print(x2[0, :]) # first row of x2

[3 5 2 4]


Imprimindo a linha de posição 0 de x2 e todas as colunas. Veja que se apenas um número é dado (ao invés de linha, coluna), o número dado é referente à linha e todas as colunas são implicitamente referidas:

In [72]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [73]:
print(x2[0]) # equivalent to x2[0, :]

[3 5 2 4]


## 5. Reformando (Reshaping)

Se pode reformatar um array para se ter o formato desejado. Por exemplo mudar o formato de vetor de 9 elementos para o formato de uma matrix de 1x9. Note que o número de elementos continua o mesmo. Assim, se deve prestar atenção ao novo formato para que este tenha o mesmo número de elementos do formato inicial. 

Um exemplo:

In [74]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
np.arange(1, 10).ndim

1

Note que o array agora em 2 dimensões tem [[ no ínicio dele e ]] no final ao invés de [ e ], indicando que não é de uma dimensão mas sim de duas. Este novo formato é de 2 dimensões, ou seja, de 1 linha e 9 colunas:

In [77]:
np.arange(1, 10).reshape(1, 9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [78]:
np.arange(1, 10).reshape(1, 9).ndim

2

Reformatando de 1x9 para 3x3:

In [79]:
grid = np.arange(1, 10).reshape((3, 3)) 
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Vejamos este caso. Temos um vetor x com 3 elementos. Reformatamos ele para ter 1 linha e 3 colunas:

In [80]:
x = np.array([1, 2, 3])

In [81]:
x

array([1, 2, 3])

In [82]:
x.reshape((1, 3))

array([[1, 2, 3]])

Podemos fazer o mesmo usando a função np.newaxis. Ela cria um novo eixo (axis), linha ou uma coluna, dependendo de onde esta função é chamada no formato, criando assim uma nova dimensão.

Por exemplo, neste caso np.newaxis cria um novo eixo na linha:

In [83]:
x

array([1, 2, 3])

In [84]:
x[np.newaxis, :]

array([[1, 2, 3]])

Neste outro exemplo, reformatamos x para ter 3 linhas e 1 coluna. Fazemos depois o mesmo com np.newaxis agora criando um novo eixo na coluna:

In [85]:
x

array([1, 2, 3])

In [86]:
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [87]:
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## 6. Concatenação

Podemos concatenar (juntar) dois ou mais arrays usando np.concatenate. Veja que os arrays que ele deve concatenar são dados dentro de uma lista, no exemplo abaixo a lista [x,y].

A ordem de concatenação é dada pela sequência de arrays na lista passada como argumento.

In [88]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [89]:
z = [77, 77, 77] 
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 77 77 77]


In [90]:
print(np.concatenate([x, z, y]))

[ 1  2  3 77 77 77  3  2  1]


Quando concatenamos/ajuntamos arrays de duas dimensões, o segundo (e outros mais) é adicionado no eixo 0 (horizontal, quer dizer abaixo) e não no eixo 1 (vertical, quer dizer do lado direito):

In [91]:
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6]])

In [92]:
np.concatenate([matrix_A, matrix_A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

Se quisermos ajuntar o novo array no lado diretio (eixo vertical, eixo 1), temos que especificar isto porque o padrão (default) é o eixo 0:

In [93]:
 np.concatenate([matrix_A, matrix_A], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

Se ajuntamos/concatenamos um array de 1 dimensão a um array de 2 dimensões, este pode ser: 
- concatenado na vertical (quer dizer, abaixo) usando np.vstack ou 
- concatenado na horizontal (quer dizer, do lado direito) usando np.stack

In [94]:
x = np.array([1, 2, 3])
matriz_A = np.array([[9, 8, 7],
                    [6, 5, 4]])

Concatenando na vertical, quer dizer abaixo, com np.vstack:

In [95]:
np.vstack([x, matriz_A])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

Concatenando na horizontal, quer dizer ao lado, com np.hstack:

In [96]:
y = np.array([[99],
              [99]])
np.hstack([matriz_A, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

## 7. Divisão (Splitting)

Podemos dividir um vetor em um certo numero de partes, respeitando o número total de elementos que deve deve permanecer o mesmo. Para isto, se usa a função np.split().

Estes são os argumentos da função

np.split(ary, indices_or_sections, axis=0)

Veja que axis = 0 (horizontal) é o padrão/default.
Se `indices_or_sections` for um número inteiro, N, a matriz será dividida em N arrays *iguais* ao longo de `axis`. Se tal divisão não for possível, um erro é levantado.

### 7.1 Divisão de vetores (arrays de 1 dimensão)

Se `indices_or_sections` for uma matriz de 1 dimensão de inteiros, se pode identificar *onde* será feito a divisão, por exemplo: 
usando divisão com argumento [2, 4] num array de 1 dimensão com axis = 0, faria uma divisão nestas posições: 

- Primeiro novo array =  array_original [:2]
- Segundo novo array = array_original [2:4]
- Terceiro novo array = array_original [4:]

Vejamos um exemplo:

In [97]:
x=[1,2,3,77,77,3,2,1] 
x

[1, 2, 3, 77, 77, 3, 2, 1]

Divida o array x em 3 partes da forma `x[:3],x[3:5],x[5:]`

In [98]:
x1, x2, x3 = np.split(x, [3, 5])

In [99]:
print(x1, x2, x3)

[1 2 3] [77 77] [3 2 1]


### 7.2 Divisão de matrizes, arrays de 2 dimensões

### 7.2.1 Na vertical com np.vsplit()

Ao se dividir uma matrix se pode usar np.vsplit() para divisão na vertical, quer dizer, ao se dividir se cria uma parte em baixo e outra em cima. O argumento entre `[]` é o índice da linha (não inclusive) onde a divisão deve ocorrer. Por exemplo:

In [100]:
matrix_A = np.arange(16).reshape((4, 4))
matrix_A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
upper, lower = np.vsplit(matrix_A, [2]) 
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


### 7.2.1 Na horizontal com np.hsplit()

Ao se dividir uma matrix se pode usar np.hsplit() para divisão na horizontal, quer dizer, ao se dividir se cria uma parte à esquerda e outra à direita. O argumento entre `[]` é o índice da coluna (não inclusive) onde a divisão deve ocorrer. Por exemplo:

In [102]:
matrix_A = np.arange(16).reshape((4, 4))
matrix_A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [103]:
left, right = np.hsplit(matrix_A, [2]) 
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## 8. Computando

Todos os operadores comuns como adição, subtração, multiplicação e outros, podem operar em arrays. Para isto, se usa broadcasting/difusão, ou seja, a operação aplicada ao array é aplicada a *cada* elemento do array. 
Vejamos vários exemplos:

In [104]:
x = np.arange(4) 

In [105]:
print("x =", x)
print("x + 5 =", x + 5) 
print("x - 5 =", x - 5) 
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2) # floor division


x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [ 0.   0.5  1.   1.5]
x // 2 = [0 0 1 1]


In [106]:
print("-x = ", -x) 
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


Uma expressão algébrica pode ser aplicada ao array x. Esta expressão é então aplicada a cada elemento do array x:

In [107]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

Numpy tem seus próprios operadores como `np.add()` para adicionar

In [108]:
np.add(x, 2)

array([2, 3, 4, 5])

In [109]:
x = np.array([-2, -1, 0, 1, 2])
abs(x)

array([2, 1, 0, 1, 2])

In [110]:
x=np.array([3-4j,4-3j,2+0j,0+1j]) 
np.abs(x)

array([ 5.,  5.,  2.,  1.])

In [111]:
x = [1, 2, 3] 
print("x =", x)
print("e^x =",np.exp(x)) 
print("2^x =",np.exp2(x)) 
print("3^x =",np.power(3,x))

x = [1, 2, 3]
e^x = [  2.71828183   7.3890561   20.08553692]
2^x = [ 2.  4.  8.]
3^x = [ 3  9 27]


In [112]:
x = [1, 2, 4, 10] 
print("x =", x)
print("ln(x) =", np.log(x)) 
print("log2(x) =", np.log2(x)) 
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [ 0.          0.69314718  1.38629436  2.30258509]
log2(x) = [ 0.          1.          2.          3.32192809]
log10(x) = [ 0.          0.30103     0.60205999  1.        ]


In [113]:
x = [0, 0.001, 0.01, 0.1] 
print("exp(x) - 1 =", np.expm1(x)) 
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [ 0.          0.0010005   0.01005017  0.10517092]
log(1 + x) = [ 0.          0.0009995   0.00995033  0.09531018]


## 9. Agregação

Numpy tem várias funções estatísticas e de agregação para descrição e sumários dos elementos de um array. É possível, por exemplo, somar todos os elementos de um array.

Algumas destas funções são já disponíveis no Python básico, mas a diferença está em algo fundamental: *velocidade*

As funções implementadas em Numpy para agirem em Numpy arrays são altamente eficientes! Vejamos um exemplo:

### 9.1 Agregação em vetores, arrays de 1 dimensão

Faremos a soma de todos os elementos de um array usando a função `sum()` de Python e depois usando a função `np.sum()` de Numpy. O resultado é o mesmo. 

In [114]:
small_array = np.random.random(200)
sum(small_array)

104.26720633300441

In [116]:
np.sum(small_array) 

104.26720633300435

A diferença está na *velocidade*. Para vermos isto, usaremos um dos assim chamados "comando mágic" do Jupyter Notebook, `%timeit`, para calcular quanto tempo leva para se executar cada uma destas duas operações:
- `sum()` de Python  e 
- `np.sum()` de Numpy 

num array com 1.000.000 (1 bilhão) de números aleatórios criados com `np.random.random()`.

In [117]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

1 loop, best of 3: 268 ms per loop
1000 loops, best of 3: 1.57 ms per loop


Da mesma forma, as funções `min()` e `max()` de Python básico e as funções `np.min()` e `np.max()` fazem respectivamente o mesmo, ou seja, encontrar o valor mínimo e o valor máximo num array. 

In [118]:
min(big_array), max(big_array)

(1.4057692298008462e-06, 0.99999943927230051)

In [119]:
np.min(big_array), np.max(big_array)

(1.4057692298008462e-06, 0.99999943927230051)

Mas a diferença está na velocidade de processamento! Veja:

In [120]:
%timeit min(big_array)
%timeit np.min(big_array)

10 loops, best of 3: 173 ms per loop
1000 loops, best of 3: 1.6 ms per loop


### 9.2 Agregação em arrays de mais de 1 dimensão,  multidimensional

O mesmo acontece com arrays de mais de 1 dimensão. Várias funções são disponíveis para se realizar operações de agregação como encontrar a soma de todos os elementos, encontrar o elemento maior, encontrar o elemento menor, etc. 

Como no caso de vetores, Python básico oferece sua própria versão destas funções de agregação. Mas as estas funções em Numpy tem uma diferença significativa: a velocidade de processamento.

Vejamos alguns exemplos com funções de Python básico e depois com as funções de Numpy:

In [121]:
matrix_A = np.random.random((3, 4)) 
matrix_A

array([[ 0.35747479,  0.16525562,  0.22801649,  0.01116173],
       [ 0.96484772,  0.93042983,  0.28571123,  0.18633432],
       [ 0.84657553,  0.11751108,  0.43646768,  0.48335078]])

#### Funções de Python básico

In [122]:
matrix_A.sum()

5.0131368007542028

Note que como agora estamos trabalhando em mais de 1 dimensão, podemos indicar em qual eixo (axis) a operação deve ser realizada. Se não indicarmos, a operação é aplicada no array como um todo.

In [123]:
matrix_A.min(axis=0) 

array([ 0.35747479,  0.11751108,  0.22801649,  0.01116173])

In [124]:
matrix_A.max(axis=1) 

array([ 0.35747479,  0.96484772,  0.84657553])

#### Funções de Numpy

In [125]:
np.sum(matrix_A)

5.0131368007542028

Função aplicada no eixo 0, temos o elemento menor em cada eixo 0:

In [126]:
np.min(matrix_A, axis = 0)

array([ 0.35747479,  0.11751108,  0.22801649,  0.01116173])

Função aplicada no eixo 1, temos o elemento maior em cada eixo 1:

In [127]:
np.max(matrix_A, axis = 1)

array([ 0.35747479,  0.96484772,  0.84657553])

Função aplicada no array como um todo:

In [128]:
np.max(matrix_A)

0.9648477168758639

In [129]:
np.mean(matrix_A)

0.41776140006285023

## 10. Broadcasting/Difusão

Como já vimos anteriormente, toda operação aplicada a um array é aplicada a *cada* um de seus elementos.

Este mesmo tipo de broadcasting/difusão é usado quando se faz operações envolvendo dois arrays, por exemplo a soma de dois arrays, cada elemento é somado ao seu elemento correspondente.

In [130]:
x = np.array([0, 1, 2])
y = np.array([5, 5, 5])
x + y

array([5, 6, 7])

In [131]:
x + 5

array([5, 6, 7])

Isto também acontece quando somamos uma array de 2 dimensões com um array de uma dimensão. Por exemplo:

In [132]:
matrix_A = np.ones((3, 3))
matrix_A

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [133]:
matrix_A + x

array([[ 1.,  2.,  3.],
       [ 1.,  2.,  3.],
       [ 1.,  2.,  3.]])